services:
  - type: web
    name: my-web-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 80"
    envVars:
      - key: DATABASE_URL
        value: postgres://<username>:<password>@<host>:<port>/<dbname>
