services:
  - type: web
    name: medical-appointment-system
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn appointments.main:app --host 0.0.0.0 --port 80"


