name: Django CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
        - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django djangorestframework drf-yasg psycopg2
    - name: Run migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate
    - name: Run tests
      run: python manage.py test
    - name: Start Django server
      run: python manage.py runserver 0.0.0.0:8000
